version: '2'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/rls
    volumes:
      - ./:/var/www/rls
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  ### PHP-FPM Container #######################################

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - "8014:8014"
      - "444:444"
    volumes:
      - ./:/var/www/rls
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network


  ### Neo4j Container #########################################

  neo4j:
    build: ./docker/neo4j
    ports:
      - "7474:7474"
      - "1337:1337"
    environment:
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_HEAP_MEMORY=2048 # configure the heap memory
      - NEO4J_CACHE_MEMORY=1G # configure the cache memory
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=false
    volumes_from:
      - volumes_data
  ### Databases Data Container ################################

  volumes_data:
    build: ./docker/volumes/data
    volumes:
      - ./data/neo4j:/var/lib/neo4j/data

networks:
  app-network:
    driver: bridge
