<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Http\Response;
use Symfony\Component\Console\Helper\Helper;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class EmployeeTest extends TestCase
{

    protected $header = [];

    protected $employeeParameter = [
        'name' => 'John Doe',
        'email' => 'johndoe@example.com',
    ];

    public function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->header['Accept'] = 'application/json';
    }

    /**
     * testOrphanEmployeeStoreShouldSuccess
     */
    public function testOrphanEmployeeStoreShouldSuccess()
    {
        $response = $this->post(route('orphanEmployeeStore'),
            $this->employeeParameter,
            $this->header
        );

        $response->assertStatus(Response::HTTP_OK);
    }

    /**
     * testOrphanEmployeeStoreWithoutNameShouldFail
     */
    public function testOrphanEmployeeStoreWithoutNameShouldFail()
    {
        unset($this->employeeParameter['name']);

        $response = $this->post(route('orphanEmployeeStore'),
            $this->employeeParameter,
            $this->header
        );

        $response->assertStatus(Response::HTTP_UNPROCESSABLE_ENTITY);
    }

    /**
     * testOrphanEmployeeStoreWithoutEmailShouldFail
     */
    public function testOrphanEmployeeStoreWithoutEmailShouldFail()
    {
        unset($this->employeeParameter['email']);

        $response = $this->post(route('orphanEmployeeStore'),
            $this->employeeParameter,
            $this->header
        );

        $response->assertStatus(Response::HTTP_UNPROCESSABLE_ENTITY);
    }
}
