<?php

namespace Tests\Feature;

use Illuminate\Http\Response;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class FolderTest extends TestCase
{
    protected $header = [];

    protected $folderParameter = [
        'name' => 'testing credentials ',
        'description' => 'testing username, passwords items',
    ];

    public function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->header['Accept'] = 'application/json';
    }

    /**
     * testFolderStoreShouldSuccess
     */
    public function testFolderStoreShouldSuccess()
    {
        $response = $this->post(url('/folder'),
            $this->folderParameter,
            $this->header
        );

        $response->assertStatus(Response::HTTP_OK);
    }

    /**
     * testFolderStoreWithoutNameShouldFail
     */
    public function testFolderStoreWithoutNameShouldFail()
    {
        unset($this->folderParameter['name']);

        $response = $this->post(url('/folder'),
            $this->folderParameter,
            $this->header
        );

        $response->assertStatus(Response::HTTP_UNPROCESSABLE_ENTITY);
    }

    /**
     * testFolderStoreWithoutDescriptionShouldFail
     */
    public function testFolderStoreWithoutDescriptionShouldFail()
    {
        unset($this->folderParameter['description']);

        $response = $this->post(url('/folder'),
            $this->folderParameter,
            $this->header
        );

        $response->assertStatus(Response::HTTP_UNPROCESSABLE_ENTITY);
    }

}
