<?php

namespace Tests\Feature;

use Illuminate\Http\Response;
use Tests\TestCase;

class TeamTest extends TestCase
{
    protected $header = [];

    protected $teamParameter = [
        'name' => 'testing credentials ',
        'description' => 'testing username, passwords items',
    ];

    public function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->header['Accept'] = 'application/json';
    }

    /**
     * testTeamStoreShouldSuccess
     */
    public function testTeamStoreShouldSuccess()
    {
        $response = $this->post(url('/folder'),
            $this->teamParameter,
            $this->header
        );

        $response->assertStatus(Response::HTTP_OK);
    }

    /**
     * testTeamStoreWithoutNameShouldFail
     */
    public function testTeamStoreWithoutNameShouldFail()
    {
        unset($this->teamParameter['name']);

        $response = $this->post(url('/team'),
            $this->teamParameter,
            $this->header
        );

        $response->assertStatus(Response::HTTP_UNPROCESSABLE_ENTITY);
    }

}
